### ISSUE TITLE
Bug - Cannot add an imported raw namespace to a project by changing the project id

### ISSUE THREAD

**Issue by yufuluo** [rancher/terraform-provider-rancher2-archive#100]
I imported a raw namespace (a namespace that's not assigned to any project) to the terraform template and changed the project_id from `<cluster_id>:<namespace_id>` to `<cluster_id>:<project_id>`. In the `.tfstate` file the project_id has been successfully updated. However, the rancher console shows that namespace is still not assigned to any project and the API shows `projectId": null`.

Here's the terraform template:

> resource "rancher2_namespace" "namespace" {
  name = "${var.namespace}"
  project_id = "${var.project_id}"
  resource_quota {
    limit {
      limits_cpu = "${var.cpu_limit}"
      limits_memory = "${var.memory_limit}"
      requests_storage = "${var.storage_request}"
    }
  }
}

**Comment by rawmind0** [comment]
This may be related with https://github.com/rancher/terraform-provider-rancher2/issues/78

What version of the provider are you using??

**Comment by yufuluo** [comment]
Hi @rawmind0 the provider is `terraform-provider-rancher2_v0.2.0_x5` and the terraform version is `v0.11.13`

**Comment by rawmind0** [comment]
Hi @yufuluo, do you mean provider version `v0.2.0-rc5`?? In this version bug should be fixed.. I can't reproduce your issue with provider version `v0.2.0-rc5` and rancher v2.2.2. What Rancher version are you using??

These are the steps that i do
```
# With TF file
resource "rancher2_namespace" "foo" {
  name = "foo"
  project_id = "<cluster_id>"
  description = "foo namespace"
  resource_quota {
    limit {
      limits_cpu = "100m"
      limits_memory = "100Mi"
      requests_storage = "1Gi"
    }
  }
}
# run 
$ terraform import rancher2_namespace.foo <cluster_id>:foo
rancher2_namespace.foo: Import complete!
  Imported rancher2_namespace (ID: foo)
rancher2_namespace.foo: Refreshing state... (ID: foo)

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
# Edit TF file to
resource "rancher2_namespace" "foo" {
  name = "foo"
  project_id = "<project_id>"
  description = "foo namespace"
  resource_quota {
    limit {
      limits_cpu = "100m"
      limits_memory = "100Mi"
      requests_storage = "1Gi"
    }
  }
}
# run 
$ terraform apply
rancher2_namespace.foo: Refreshing state... (ID: foo)

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ rancher2_namespace.foo
      project_id:       "<cluster_id>" => "<project_id>"

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

rancher2_namespace.foo: Modifying... (ID: foo)
  project_id:       "<cluster_id>" => "<project_id>"
rancher2_namespace.foo: Modifications complete after 4s (ID: foo)

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```
And namespade is moved to `<project_id>`...

Please, verify that you are using latest provider version. You could also use official version that was released yesterday, https://github.com/terraform-providers/terraform-provider-rancher2/releases

**Comment by rawmind0** [comment]
Due to rancher2 terraform provider is already officially supported by Hashicorp, this repo is going to be archived.

Please consider reopen issue on https://github.com/terraform-providers/terraform-provider-rancher2 if needed.
