### ISSUE TITLE
Timeout for resources should be configurable

### ISSUE THREAD

**Issue by Oats87** [rancher/terraform-provider-rancher2-archive#19]
Timeout for resources (specifically clusters) should be configurable. For example, while performing provisioning of an EKS cluster, it is quite possible that can take longer than 10 minutes for provisioning to occur. We should allow timeouts to be configurable to allow users to provision EKS/etc. clusters and other resources that may take longer than 10 minutes to provision.

**Comment by rawmind0** [comment]
Merged PR. Please reopen issue if needed.
