### ISSUE TITLE
EKS Cluster Instance Type is not passed to Rancher properly

### ISSUE THREAD

**Issue by Oats87** [rancher/terraform-provider-rancher2-archive#20]
While provisioning an EKS cluster using the Terraform provider, no matter the value passed to `instance_type`, it will always fail with: 

```
Error creating stack: error creating master: ValidationError: Parameter NodeInstanceType failed to satisfy constraint: Must be a valid EC2 instance type status code: 400, request id: efec7d16-ffd5-11e8-a8c1-0177a3c23abe
```

**Comment by rawmind0** [comment]
Merged PR that solves this issue, https://github.com/rancher/terraform-provider-rancher2/pull/21

Please, reopen issue if needed.
