### ISSUE TITLE
NodeTemplate to support OpenStackConfig

### ISSUE THREAD

**Issue by SquishyMochi514** [rancher/terraform-provider-rancher2-archive#27]
Rancher2 provider started to support NodeTemplates. It would be  nice to support OpenStack as well.

**Comment by rawmind0** [comment]
@speedfire514 support OpenStack NodeTemplate is on the backlog. A PR for it, would be very appreciated. ;)

**Comment by rodcloutier** [comment]
The build fails but the error is actually in the master branch.

**Comment by rawmind0** [comment]
Added support to openstack cloud credential and node template on PR #91

**Comment by rawmind0** [comment]
Please, reopen if needed.
