### ISSUE TITLE
`extra_binds` and `fail_swap_on` missing in kubeproxy and kubelet fields

### ISSUE THREAD

**Issue by terciodemelo** [rancher/terraform-provider-rancher2-archive#29]
I'd like to use this provider but I need to set `extra_binds` to kubeproxy and `fail_swap_on` on kubelet services. In my current Rancher2 clusters I set these fields in the cluster config yaml.

I'd like to know if these configs are in the plan to be made available? If you're short on hand I can try to code it myself and submit a PR

**Comment by terciodemelo** [comment]
#30 solves this issue

**Comment by rawmind0** [comment]
Solved by PR #32
