### ISSUE TITLE
Can not provide ami image when createing AWS EKS cluster which is possible via the Rancher UI

### ISSUE THREAD

**Issue by ajfriesen** [rancher/terraform-provider-rancher2-archive#38]
When creating a AWS EKS cluster it will automaticly create an EKS cluster with version 1.11 which is fine.

But the worker nodes have an old ami image:
* ami-0440e4f6b9713faf6

This image will create a worker with:
* Docker version: 17.6.2
* Kubernetes Version: v1.10.3

We can not provide a ami image with the provider as we could in the UI.

When we create an AWS EKS cluster via the Rancher UI it is possible to override the default ami image with something like this ami-0eeeef929db40543c which we get from here [Amazon EKS-Optimized AMI](https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-ami.html)

This will create an a worker with:
* Docker version: 18.6.1
* Kubernetes Version: v1.11.5

It seems it is just not implemented yet when I had a look into this file:
[cluster_eks_config.go](https://github.com/rancher/terraform-provider-rancher2/blob/master/rancher2/cluster_eks_config.go#L14)

**Comment by rawmind0** [comment]
Added  #a commit to PR #37 to add `ami` and `associate_worker_node_public_ip` fields on eks cluster config. #37

**Comment by ajfriesen** [comment]
Just tested this. Everything seems to work as expected.

**Comment by rawmind0** [comment]
Thanks for the feedback @ajfriesen. PR #37 is already merged, please reopen issue if needed.
