### ISSUE TITLE
Terraform Provider Development Program Review

### ISSUE THREAD

**Issue by cgriggs01** [rancher/terraform-provider-rancher2-archive#39]
Hey Bill and Raul, 

I’ve taken a look at the provider here and would like to say great work so far! I do have feedback outlined below that I’d like to see addressed before we move on to the next steps. I’m opening this issues as a sort of checklist for tracking items and discussion. The review was done on the master branch at git commit `87c3712`.

- [x] The makefile should be  replaced with  the GNUmakefile which is standard across all Terraform providers, feel free to copy the [NULL provider makefile](https://github.com/terraform-providers/terraform-provider-tls/blob/master/GNUmakefile) and will just have to update the variable on line 4 to PKG_NAME=rancher2
	-  [x] This includes a change to use Go Modules for dependency management
	- [x] There are four bash scripts kept in a scripts/ directory that are used in different processes of testing and release, these can all be copied from the [NULL provider](https://github.com/terraform-providers/terraform-provider-null/tree/master/scripts) 
	- [x] Since this provider is tested against a docker image the scripts for start-rancher should be under the `testacc` make target. 
 - [x] Each Terraform provider must have a CHANGELOG that is updated during reach release. Since the changeling is updated by a bot during the release it must be in a certain format. With the [AWS provider changelog](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md) as an example, the version of the next release should be tagged as “(Unreleased)” and will then be updated with a date by the release-bot. 
- [x] All providers in the terraform-providers/ GitHub org have a TravisCI check run on each PR that is opened. Can you please add a .travis.yaml file to make the [standard configuration](https://github.com/terraform-providers/terraform-provider-null/blob/master/.travis.yml)
- [x]  There is a standard README.md for of the official provider, see [Null provider README.md](https://github.com/terraform-providers/terraform-provider-null/blob/master/README.md)

In addition to the items listed above, there are a number of Terraform provider code expectations/conventions that have been identified by the Terraform engineering team. 

 - resource filename matches convention `resource_providername_resource_name.go`
- data source filename matches convention `data_source_providername_resource_name.go`
 -  we always let `d.Set()` to dereference pointers safely to avoid crashes, i.e. there's nothing like `d.Set(*variable)`
 - flatteners and expanders are in `structures.go` + tests in `structures_test.go`
 - any validation functions longer than a few lines are in `validators.go` + tests in `validators_test.go`
 - `d.Set()` is called in any C/R/U/D for all available fields unless they're Computed-only (i.e. there are no orphans)
 - all of `d.Set()`, `d.Get()`, `d.GetOk()`, `d.GetChange()` etc. use real field names (i.e. no typos)
 - `d.Set()` is _always_ error-checked if it’s set, list or map
 - `d.Set()` is _never_ error-checked if it's primitive data type (string, int, float, bool)
 - Resource uses either `Read` or `Exists` function to remove resource from state if it's gone
 - `d.Partial()` & `d.SetPartial()` are used any time there's more than 1 API call used to create or update a resource.
 - `schema.ForceNew` is used for any field that is not updatable
 - all field names are `lowercase_underscore`
 - where possible data source fields match resource (e.g. when referencing `aws_instance` user shouldn't need to change anything - just add `data.` prefix)
 - Constants are used if there are available in the upstream SDK (e.g. for status codes)
 - `[INFO]` log message at least 2 per each C/R/U/D - e.g. creating (input), created (output)
 - The provider code does not `panic`, always returns errors

Let me know if you have any questions.
Best,
Chris

**Comment by rawmind0** [comment]
Hi Chris,

we've already created a PR to address all these items, https://github.com/rancher/terraform-provider-rancher2/pull/31 . Could you please review it, instead of master branch??

Thanks

**Comment by cgriggs01** [comment]
Closing this issue as all feedback has been address, will open a new issue with addition feedback shortly.
