### ISSUE TITLE
Create workload from terraform

### ISSUE THREAD

**Issue by langoureaux-s** [rancher/terraform-provider-rancher2-archive#4]
Hi,

you wil expanse this current provider to permit to deploy workload on Kubernetes, or we need  to use another terraform plugin to do that like "Kubernetes Provider" ?

Or maybee a best way is to use helm or kubctl for this purpose (IaC for workload) ?

**Comment by gaui** [comment]
I'd recommend using the official Kubernetes package manager, [Helm](https://helm.sh) and the [Terraform Helm provider](https://www.terraform.io/docs/providers/helm/) for specific deployments, otherwise Rancher.

**Comment by rawmind0** [comment]
Hi @langoureaux-s, 

btm, expanse the current provider with workloads is not on the backlog . As commented @gaui , it's recommended to use the official terraform kubernetes or helm providers to deploy workloads.
