### ISSUE TITLE
rancher2 provider

### ISSUE THREAD

**Issue by virtrixke** [rancher/terraform-provider-rancher2-archive#40]
testing the rancher2 terraform provider on windows.
I downloaded the release (terraform-provider-rancher2_windows-amd64.exe) and put it under the default plugin location (.terraform/plugins/windows_amd64) and added a main.tf with the following content:

```
provider "rancher2" {
  api_url    = "https://rancher.test.somedomain.local"
  access_key = "token-f8fortg"
  secret_key = "xxx"
}
```

However, the terraform init command complains that it cannot find the rancher2 provider. 
Any idea?

**Comment by rawmind0** [comment]
@virtrixke, have you tried configuring [terraform third-party-plugins](https://www.terraform.io/docs/configuration/providers.html#third-party-plugins)?? Default terraform plugin path for windows is `%APPDATA%\terraform.d\plugins`

Also, you could try configuring [terraform provider plugin cache](https://www.terraform.io/docs/configuration/providers.html#provider-plugin-cache)

**Comment by sosoriov** [comment]
@rawmind0  thanks for your hint. 
I downloaded the plugin manually and rename it to *terraform-provider-rancher2.exe* I got rid off the windows..xx part in the file name, in that way Terraform was able to detect the provider

@virtrixke

**Comment by ajfriesen** [comment]
You have to do the same on linux as well.

**Comment by rawmind0** [comment]
@sosoriov and @ajfriesen, thanks for your comments. 

@virtrixke, please reopen issue if needed.
