### ISSUE TITLE
No option for desired number of nodes for Autoscaling Group in AWS

### ISSUE THREAD

**Issue by ajfriesen** [rancher/terraform-provider-rancher2-archive#43]
When creating an AWS EKS cluster it is not possible to set the desired number of nodes for the autoscaling group.

I think it will always create as many nodes as are set for maximum nodes. At least this is the behavior we have seen in our last tests.

This setting can not be set via a manual setup through the rancher ui either. So maybe I need to open an issue regarding this in rancher itself.

**Comment by rawmind0** [comment]
@ajfriesen, there is no option on rancher2 EKS driver to set desired number of nodes for autoscaling group [kontainer-engine eks driver](https://github.com/rancher/kontainer-engine/blob/master/drivers/eks/eks_driver.go#L123)

By default, autoscaling group would create as many nodes as are set for minimum nodes, if desired nodes is not specified, [autoscaling-ec2](https://docs.aws.amazon.com/autoscaling/ec2/userguide/as-maintain-instance-levels.html)

If you'd need this feature, please open it at rancher repo.
