### ISSUE TITLE
Deleting a cluster returns before cluster is actually deleted

### ISSUE THREAD

**Issue by mhulscher** [rancher/terraform-provider-rancher2-archive#44]
When deleting a resource of type `rancher2_cluster` terraform will assume the resource as deleted before the cluster is actually removed. The cluster CRD will still exist and potentially fail to be finalized because any nodes may have already been removed.

Perhaps cluster deletion could be an async job?

**Comment by rawmind0** [comment]
@mhulscher, cluster deletion is an async job, it'll be eventually deleted. 
`rancher2_cluster` is marked as `removed` if cluster `IsNotFound` or if `cluster.Removed != ""` 
[clusterStateRefreshFunc](https://github.com/rancher/terraform-provider-rancher2/blob/master/rancher2/resource_rancher2_cluster.go#L499)

Are you suffering any concrete issue with it??

**Comment by mhulscher** [comment]
I updated both rancher to the latest rc and the terraform provider to the latest release. I can no longer reproduce the problem. Closing this issue :)
