### ISSUE TITLE
KUBECONFIG resource for kubernetes and helm

### ISSUE THREAD

**Issue by ajfriesen** [rancher/terraform-provider-rancher2-archive#48]
This provider does not  create a resource for the kubeconfig when creating an AWS EKS cluster.

For now when we create the AWS EKS cluster with this provider we have to go to the rancher ui and get the kubeconfig. Afterwards we need to reference the the kubernetes config with the file we just downloaded like.

Would it be possible to get the resource KUBECONFIG_FROM_YOUR_CREATED_CLUSTER and use that as input for the kubernetes and helm provider?

**Comment by rawmind0** [comment]
Good point @ajfriesen... I've submitted PR #49 to add kube_config computed field on cluster resources.

**Comment by rawmind0** [comment]
@ajfriesen, PR #49 is already merged. Please, reopen issue if needed.
