### ISSUE TITLE
AWS EKS security groups for EKS cluster and worker nodes

### ISSUE THREAD

**Issue by ajfriesen** [rancher/terraform-provider-rancher2-archive#50]
When creating an AWS EKS cluster you can provide a list of security groups for the AWS EKS cluster which will be attached to the cluster.

But rancher or EKS (not sure) will also create a security group for the worker nodes as well.
This resource is not managed by the provider as of now and therefore terraform does not know anything about this.

Should this go into provider so that we:

* can define our own security groups and rules
* also control the security groups from terraform

**Comment by cloudnautique** [comment]
The flow the provider will follow calls Rancher, which will create the cluster in AWS through the kontainer-engine. Ultimately, kontainer-engine calls cloud formation and other AWS APIs. None of those resources will be known to this provider. This provider really only knows about the cluster object in Rancher. 

You can pass a list of Security Group IDs, which you can use the AWS TF provider to create.

I'm not really sure I follow on the second ask. Can you clarify?

**Comment by ajfriesen** [comment]
I try to clarify:
Is there a rancher api available for the security groups for the worker nodes?
 
# Why we ask this question:
 
We first create a network stack for our EKS cluster.
* VPC
* pubilc subnet
* private subnet
* vpc peering and what not
 
Afterwards we create the EKS cluster into that specific VPC.
We encounter a few problems:
 
1. We can not tag our subnets like described here #51 to create a network loadbalancer via a kubernetes nginx-ingress controller
2. To Fix the above, we added the public subnet to the EKS config and "allowed public ip = true". This helped in creating the worker nodes with public IP. This still looks like a workaround though.
3. The worker nodes are not reachable from the network loadbalancer as the security groups dont allow traffic when the security group is created not by terraform (EKS/Rancher- we dont know). Since the security group can not be edited by terraform we can not automatically open our port for the AWS NLB.

**Comment by rawmind0** [comment]
Due to rancher2 terraform provider is already officially supported by Hashicorp, this repo is going to be archived.

Please consider reopen issue on https://github.com/terraform-providers/terraform-provider-rancher2 if needed.
