### ISSUE TITLE
Tagging public subnet in AWS to create an AWS Loadbalancer

### ISSUE THREAD

**Issue by ajfriesen** [rancher/terraform-provider-rancher2-archive#51]
When creating an AWS EKS cluster with private and public subnets we only choose to place the workers into the private subnet.

The private subnet then does got the right tag for kubernetes like this:

```
kubernetes.io/cluster/<CLUSTER-ID> | shared
```

When we want to create a internet facing Loadbalancer with kubernetes we need to provide some special tags to the public subnets:

```
kubernetes.io/cluster/<CLUSTER-ID> | shared
kubernetes.io/role/elb
```
Since we first create the network with terraform on aws we do not know the **CLUSTER-ID** when creating the subnet.

How can we provide both tags for the public subnets to create a loadbalancer in aws?

I am not sure if this is a problem by the rancher2 terraform provider or rancher itself.

**Comment by rawmind0** [comment]
Due to rancher2 terraform provider is already officially supported by Hashicorp, this repo is going to be archived.

Please consider reopen issue on https://github.com/terraform-providers/terraform-provider-rancher2 if needed.
