### ISSUE TITLE
Shouldn't leak sensitive data

### ISSUE THREAD

**Issue by yamamoto-febc** [rancher/terraform-provider-rancher2-archive#53]
(from: https://github.com/yamamoto-febc/terraform-provider-rke/issues/60)

In [terraform-provider-rke](https://github.com/yamamoto-febc/terraform-provider-rke), we encountered a case where sensitive data – such as a private key – leaked because `Sensitive: true` is not set.

I think this provider has same issue.  
Because it seems that this provider is not set to `Sensitive: true` at all.

**Comment by rawmind0** [comment]
Thanks for the advice @yamamoto-febc.. We are going to review and submit a PR solving it.

**Comment by rawmind0** [comment]
Submitted PR #54 to solve this issue.

**Comment by rawmind0** [comment]
Thanks @yamamoto-febc. 

Merged PR #54 to solve it. Please reopen issue if needed.
