### ISSUE TITLE
Get resource fields instead of kube_config file

### ISSUE THREAD

**Issue by ajfriesen** [rancher/terraform-provider-rancher2-archive#56]
Thanks for the generated kube_config file. (#48)
The problem we have now is that you have to have the kuber_config file locally to use it.

Would it be possible to get the resource fields like the kubernetes provider is expecting them:

https://www.terraform.io/docs/providers/kubernetes/index.html#statically-defined-credentials

**Comment by rawmind0** [comment]
@ajfriesen, have you consider to use terraform [local_file](https://www.terraform.io/docs/providers/local/r/file.html) to write kube_config instead of terraform output??

**Comment by mhulscher** [comment]
I would also enjoy being able to use the individual fields to configure the Kubernetes provider. Especially in CI pipelines it is cumbersome and unwanted to use the local_file resource. 

The community RKE provider seems to solve this well: https://github.com/yamamoto-febc/terraform-provider-rke#with-kubernetes-provider

```hcl
provider "kubernetes" {
  host     = rancher2_cluster.cluster.api_server_url
  username = rancher2_cluster.cluster.kube_admin_user

  client_certificate     = rancher2_cluster.cluster.client_cert
  client_key             = rancher2_cluster.cluster.client_key
  cluster_ca_certificate = rancher2_cluster.cluster.ca_crt
  # load_config_file = false
}```

**Comment by mhulscher** [comment]
@ajfriesen 
I created a wrapper module around the rancher2_cluster resource for various reasons. I now return the token and the server address like such:

```hcl
output "kubernetes_server" {
  sensitive   = true
  description = "Address of the kube-apiserver"
  value       = "${replace(rancher2_cluster.cluster.kube_config, "/(?ms)^.*server: \"(.+?)\".*$(?ms)/", "$1")}"
}

output "kubernetes_token" {
  sensitive   = true
  description = "Token to access the kube-apiserver"
  value       = "${replace(rancher2_cluster.cluster.kube_config, "/(?ms)^.*token: \"(.+?)\".*$(?ms)/", "$1")}"
}
```

**Comment by rawmind0** [comment]
Due to rancher2 terraform provider is already officially supported by Hashicorp, this repo is going to be archived.

Please consider reopen issue on https://github.com/terraform-providers/terraform-provider-rancher2 if needed.
