### ISSUE TITLE
how to create a cluster, add cusom nodes and all with terraform on rancher 2?

### ISSUE THREAD

**Issue by mihai-satmarean** [rancher/terraform-provider-rancher2-archive#57]
Hi, 

the thinks are moving fast,  and in the right direction
thanks for that!

I would like to have the possibility to create a cluster and add custom nodes that are physical computers running docker.
All with terraform and Rancher 2.
Currently I cannot find the documentation to do that.

Thank you!

**Comment by rawmind0** [comment]
Hi @mihai-satmarean, on provider docs you have documented some examples of [creating a cluster](https://github.com/rancher/terraform-provider-rancher2/blob/master/website/docs/r/cluster.html.markdown#example-usage)

If you want custom cluster, adding physical nodes running docker, you'd need to create a new rancher2 rke cluster.
```
# Create a new rancher2 rke Cluster 
resource "rancher2_cluster" "foo-custom" {
  name = "foo-custom"
  description = "Foo rancher2 custom cluster"
  kind = "rke"
  rke_config {
    network {
      plugin = "canal"
    }
  }
}
```

Once it's created, you'll get a exported field called [`cluster_registration_token`](https://github.com/rancher/terraform-provider-rancher2/blob/master/website/docs/r/cluster.html.markdown#attributes-reference). This field contains `node_command` that is the command to execute in your nodes to build the rke cluster. Take into account that you need to add parameters `--etcd`,  `--controlplane` and/or `--worker` to the command depending the roles of your nodes.

Also, take a look on [node requirements](https://rancher.com/docs/rke/v0.1.x/en/os/) to check software, size and network requirements.

**Comment by rawmind0** [comment]
Please reopen if it's needed.
