### ISSUE TITLE
ADFS rancher_api_host should be rancher_api_url

### ISSUE THREAD

**Issue by Mikulas** [rancher/terraform-provider-rancher2-archive#60]
When setting the `rancher_api_host` on `resource rancher2_auth_config_adfs`, it is saved into Rancher incorrectly. Rancher interface expects the field to be a URL, not a host, and strips the first 8 characters assuming it is `https://`.

Rancher2 provider should either replace this parameter with `rancher_api_url` which then also simplifies the config as it can be set to `${rancher2_setting.server-url.value}` OR it should append the `https://` automatically.

The current solution works when user explicitly sets the _host_ to value with `https://…` but that's a misnomer.

Example:
```
rancher_api_host = "mg-rancher.mgit.cz"
```
results in
![Screenshot 2019-03-26 at 14 28 29](https://user-images.githubusercontent.com/192200/55000822-a23b4d80-4fd3-11e9-8805-8c42476f14dd.png)

**Comment by rawmind0** [comment]
Hi @Mikulas, yeah this is a bug with the current provider. I'm working on a PR to address it and issue #59 . I'll submit it asap.

**Comment by rawmind0** [comment]
Submited PR to fix this issue, https://github.com/rancher/terraform-provider-rancher2/pull/61

**Comment by rawmind0** [comment]
Please, reopen if needed.
