### ISSUE TITLE
Update to terraform 0.12

### ISSUE THREAD

**Issue by drpebcak** [rancher/terraform-provider-rancher2-archive#63]
Terraform 0.12 is in beta now, and should be releasing sometime soon. Can we update the rancher2 provider to work with 0.12? It should be backwards compatible with 0.11.

**Comment by rawmind0** [comment]
Due to rancher2 terraform provider is already officially supported by Hashicorp, this repo is going to be archived.

Please consider reopen issue on https://github.com/terraform-providers/terraform-provider-rancher2 if needed.
