### ISSUE TITLE
HashiCorp Terraform Provider Development Review 

### ISSUE THREAD

**Issue by cgriggs01** [rancher/terraform-provider-rancher2-archive#67]
Hey Raul,

Thanks for all you work on this provider so far, its looking better and better. One this I'd like to get passing is the nightly acceptance test from the terraform-provider [nightly acceptance testing](https://ci-oss.hashicorp.engineering). I've fixed you account and you should not have access to the Rancher2 acceptance test environment.

- [x]  For organizational simplicity, all terraform providers use `structure.go` and `structure_test.go` for all flattener and expander functions.  

- [x] Each resource import function should be under their own, `import_rancher2_<resource>.go`

- [x] On the Rancher2 index page and `provider.go` the argument reference `api_url` is listed as required in the documentation but in the resource schema is defined as optional. 

- [x] In the Cluster resource documentation page, there are some formatting errors with the HCL code blocks and this page could be cleaned up a little bit. 

- [x] The `resource_rancher2_node_template.go` file out of format. This can be fixed by simply running `make fmt` on the provider. 

- [x] The acceptance tests currently cover ~35% of the code base. Ideally we like to have at least 50% code coverage with these tests. As well the follow resources do not have a corresponding test file.  
```
resource_rancher2_auth_config_activedirectory.go
resource_rancher2_auth_config_adfs.go
resource_rancher2_auth_config_azuread.go
resource_rancher2_auth_config_freeipa.go
resource_rancher2_auth_config_github.go
resource_rancher2_auth_config_openldap.go
resource_rancher2_auth_config_ping.go
resource_rancher2_node_pool.go
```
If there is a specific reason this resources do not have tests written for them, let me know and we can discuss it. 

The final most important thing is to get all the acceptance test passing inside of TeamCity. 

Looking forward to releasing this with you.

**Comment by rawmind0** [comment]
Hey Chris, 

thanks for the feedback. Working on a PR for address all these points.

**Comment by rawmind0** [comment]
> * [x]  For organizational simplicity, all terraform providers use `structure.go` and `structure_test.go` for all flattener and expander functions.  

Also added `schema.go` files for organizational simplicity.
Fixed on PR #84. 

> * [x] Each resource import function should be under their own, `import_rancher2_<resource>.go`

Fixed on PR #77. 

> * [x] On the Rancher2 index page and `provider.go` the argument reference `api_url` is listed as required in the documentation but in the resource schema is defined as optional. 

Fixed on PR #76 

> * [x] In the Cluster resource documentation page, there are some formatting errors with the HCL code blocks and this page could be cleaned up a little bit. 

Fixed on PR #76. 

@cgriggs01, please take a look to the updated docs format and HCL. We've added `nested block` section to make clean up the format.

> * [x]  The `resource_rancher2_node_template.go` file out of format. This can be fixed by simply running `make fmt` on the provider.

The issue here is due to golang version. Fixed on PR #72 

> * [x]  The acceptance tests currently cover ~35% of the code base. Ideally we like to have at least 50% code coverage with these tests. As well the follow resources do not have a corresponding test file.
> 
> ```
> resource_rancher2_auth_config_activedirectory.go
> resource_rancher2_auth_config_adfs.go
> resource_rancher2_auth_config_azuread.go
> resource_rancher2_auth_config_freeipa.go
> resource_rancher2_auth_config_github.go
> resource_rancher2_auth_config_openldap.go
> resource_rancher2_auth_config_ping.go
> resource_rancher2_node_pool.go
> ```
> If there is a specific reason this resources do not have tests written for them, let me know and we can discuss it.

There was a reason for auth_config resources didn't have go tests. They were testing to log users after update config, then they needed to have all auth backends installed and configured. We've removed the log in test and implemented go tests. Fixed on PR #61 

Also added tests for node_pool resource. Fixed on PR #71 

Once PR #84  is merged, the acceptance tests will cover ~74% of the code base.

> The final most important thing is to get all the acceptance test passing inside of TeamCity.

About that, do we need to define a Teamcity pipeline definition file?? 
Taking a look to the logs, it seems that is failing on `step 4 GoAccTestRunner`. The command to execute should be `make testacc` that would execute [scripts/gotestacc.sh](https://github.com/rancher/terraform-provider-rancher2/blob/master/scripts/gotestacc.sh) to deploy a dockerized rancher system before run the acceptance tests.

**Comment by rawmind0** [comment]
Hey @cgriggs01, 

could you please take a look?? Thanks.

**Comment by cgriggs01** [comment]
Hey Team, 

Apologies for the wait but, we were able to make a second final review pass over the provider and just have a few more feedback items to address the first two are required while the latter are more of a suggestions and not required for the release. Once complete, we can move forward to the migration and release process. 

- [x] The resource `AuthConfigPing` has argument `rancher_api_host` which is declared as "Required" in the [documentation](https://github.com/rancher/terraform-provider-rancher2/blob/master/website/docs/r/authConfigPing.html.markdown) but defined as optional in the [resource schema](https://github.com/rancher/terraform-provider-rancher2/blob/master/rancher2/schema_auth_config_ping.go#L27). 

- [x] There are some formatting error on your code blocks of the [Cluster resource documentation](https://github.com/rancher/terraform-provider-rancher2/blob/master/website/docs/r/cluster.html.markdown). You'll need to add an indent, or empty line above each of the `hcl` code blocks. For some reason our system cannot handle this formatting. 

- For consistency and ease of use, we try to group the "Required" arguments at the top of the schema and documentation. 

- While the error checking of every d.Set() complex attribute (i.e. type map, list, set) is required, it is not required to error checked d.Set() for each simple argument type(sting, int, bool). This is seen as little overly verbose because if it is incorrect, its failure will be much more obvious most likely. 

Again you are not required to fix those, but they were identified. 

The last issue we're having is with regards to the testing, we have not been successful in running the tests from our TeamCity instance, but since we were able to run them locally we can move forward with the release, and address the testing once the providers repository have been migrated to the terraform-providers/ organization. 

Thank you for your work to build this, I look forward to releasing it with you.

**Comment by rawmind0** [comment]
Hey @cgriggs01,

> - [x] The resource `AuthConfigPing` has argument `rancher_api_host` which is declared as "Required" in the [documentation](https://github.com/rancher/terraform-provider-rancher2/blob/master/website/docs/r/authConfigPing.html.markdown) but defined as optional in the [resource schema](https://github.com/rancher/terraform-provider-rancher2/blob/master/rancher2/schema_auth_config_ping.go#L27). 
> - [x] There are some formatting error on your code blocks of the [Cluster resource documentation](https://github.com/rancher/terraform-provider-rancher2/blob/master/website/docs/r/cluster.html.markdown). You'll need to add an indent, or empty line above each of the `hcl` code blocks. For some reason our system cannot handle this formatting. 
> - [x] For consistency and ease of use, we try to group the "Required" arguments at the top of the schema and documentation. 
> - [x] While the error checking of every d.Set() complex attribute (i.e. type map, list, set) is required, it is not required to error checked d.Set() for each simple argument type(sting, int, bool). This is seen as little overly verbose because if it is incorrect, its failure will be much more obvious most likely. 

All 4 items are fixed on PR #95 , please take a look.

The acceptance tests are passing almost fine locally and covering around 75% of the code. The error on your teamcity instance may be the `Working directory` setting on the step 4. Please, take a look to the email i sent you.
`setting` resource acceptance tests are failing on rancher v2.2 due to an [issue](https://github.com/rancher/rancher/issues/19705) with this release, but would be solved on rancher v2.3

**Comment by cgriggs01** [comment]
Thanks for the update.

Yes, its come to my attention that the TeamCity acceptance testing doesn't run from the provider repo directory, and theres are specific build step in TC to start docker. At this time, we will move forward and attempt running acceptance test on Travis for each PR.

Are you ready to begin the release process? We can start today, and hopefully complete by EOD tomorrow. Since there are a number of steps to migrate and release the provider. 

Thanks 
Chris

**Comment by rawmind0** [comment]
@cgriggs01 , thanks for the update.

Sure, we are ready to begin the release process. Please, tell us what would be the process steps to follow.

**Comment by rawmind0** [comment]
Rancher2 provider is just released as official supported provider, https://github.com/terraform-providers/terraform-provider-rancher2

Thanks @cgriggs01 , please reopen issue if needed.
