### ISSUE TITLE
rancher2_cluster cluster_registration_token should return a map

### ISSUE THREAD

**Issue by jgreat** [rancher/terraform-provider-rancher2-archive#68]
Maybe a repeat of #11.  

terraform-provider-rancher2 version 0.2.0-rc2

Returning a list here for a cluster doesn't seem to make sense. In what situations are you going to have more than one instance of this info? 

For ease of use I recommend flattening this map out to individual top level values like `rancher2_cluster.clustername.node_command`.  Working with nested values can be annoyingly difficult in terraform <=0.11.  (hopefully better in 0.12)

**Comment by rawmind0** [comment]
@jgreat , 

cluster_registration_token is a list but with maxItems set to 1, always referenced as index 0, `rancher2_cluster.clustername.0.node_command`.  

Agreed with you that working with nested values can be annoyingly difficult in terraform <=0.11. Because of data structure, it seems that `typeList` was the best terraform aggregated type fit.

**Comment by jgreat** [comment]
I found this really confusing when trying to work with the resource. The documentation doesn't specify that its a list.

I don't have a document to back this up, but it seems to me that best practice is to return simple lists of strings, or simple key/value pairs.  This is returning list with a nested map.

**Comment by rawmind0** [comment]
Updated documentation specifying that it's a list.

Not sure about your best practices comment. Afaik, for nested structured data the best fit on terraform aggregated type, is a `typeList`. `TypeMap ` is better for unstructured data.

**Comment by rawmind0** [comment]
Due to rancher2 terraform provider is already officially supported by Hashicorp, this repo is going to be archived.

Please consider reopen issue on https://github.com/terraform-providers/terraform-provider-rancher2 if needed.
