### ISSUE TITLE
EKS Cluster name

### ISSUE THREAD

**Issue by eromano** [rancher/terraform-provider-rancher2-archive#69]
HI guys, I am using the provider to create a cluster on eks but I don't see any way to specify a name for the cluster https://github.com/rancher/terraform-provider-rancher2/blob/1cafc314d1fa856bd192269d2f87f4c17b85906d/website/docs/r/cluster.html.markdown.
Can someone help me with it?
Thanks

**Comment by rawmind0** [comment]
Hi @eromano , the first argument for cluster resource is name,
https://github.com/rancher/terraform-provider-rancher2/blob/1cafc314d1fa856bd192269d2f87f4c17b85906d/website/docs/r/cluster.html.markdown#argument-reference

**Comment by mteodori** [comment]
thanks @rawmind0 but we set that value and it shows on the rancher UI/API enry but the backing EKS cluster is created with the name c-something which is actually the id on the Rancher UI, I wonder if the issue is here or rather on the Rancher2 installation we have which is v2.1.7

**Comment by rawmind0** [comment]
If it's the case, may be is better to open issue on [rancher](https://github.com/rancher/rancher) repo.

**Comment by rawmind0** [comment]
Please, reopen if it's needed.

**Comment by mteodori** [comment]
thanks @rawmind0 I can confirm all is good with latest rancher v2.2.2
