### ISSUE TITLE
rancher2_node_template doesn't support cloudCredentialId

### ISSUE THREAD

**Issue by simonmcc** [rancher/terraform-provider-rancher2-archive#73]
`cloudCredentialId` is now mandatory in Rancher v2.2.1 (API v3), the `rancher2_node_template`, resource doesn't support it yet, I'll start working on a PR in the next few days if it's not already in progress somewhere.

**Comment by brianmerrick** [comment]
Very interested in this as well. Any ETA on when it might be merged in?

**Comment by rawmind0** [comment]
Added support to cloud credential on PR #85

**Comment by rawmind0** [comment]
Please reopen if needed.
