### ISSUE TITLE
Question: Does this provider already work with the rancher 2.2 stable release?

### ISSUE THREAD

**Issue by ajfriesen** [rancher/terraform-provider-rancher2-archive#79]
Rancher v2.2.2 was just release as stable version.
Is this already integrated?

**Comment by dahendel** [comment]
@ajfriesen I just tried it and it does not work. Looks like there were a lot of updates

**Comment by drpebcak** [comment]
@dahendel in your experience, what did not work?

**Comment by rawmind0** [comment]
Rancher v2.2 is still not supported by this provider. We are on the way to support it soon.

**Comment by rawmind0** [comment]
Added support to rancher v2.2.x on PR #85

**Comment by rawmind0** [comment]
Please reopen if needed.
