### ISSUE TITLE
Add weave to rke_config network plugin

### ISSUE THREAD

**Issue by wkonderla** [rancher/terraform-provider-rancher2-archive#8]
Support for weave was added to rke about a year ago.

https://github.com/rancher/rke/pull/81

However it does not appear to be a supported option for the terraform provider.

**Comment by rawmind0** [comment]
Weave is not supported yet on Rancher v2.x custom cluster creation. We're working on this way.

https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/options/

**Comment by rawmind0** [comment]
Added weave support to rke_config on PR #85
