### ISSUE TITLE
When using the provider over VPN - Dialer doesn't respect VPN settings on Mac OS

### ISSUE THREAD

**Issue by vsabella** [rancher/terraform-provider-rancher2-archive#80]
When I try to access rancher2.mydomain.net from my VPN (mydomain.net DNS is within the VPN) it fails to lookup.

Error: Error running plan: 1 error(s) occurred:

* provider.rancher2: Get https://rancher2.mydomain.net/v3: dial tcp: lookup rancher2.mydomain.net on 192.168.0.1:53: no such host

Instead of just trying to connect and letting it fail if it can't resolve, it looks like it does an explicit lookup and picks the wrong nameservers?

It shouldn't be using the 192.168.0.1 nameserver, not sure why its not using vpn connection provided nameservers like all the other software.

**Comment by vsabella** [comment]
I haven't tested on Linux but I worked around with a hosts file.

**Comment by rawmind0** [comment]
@vsabella, terraform should get the dns configuration from the OS, and tf provider is just using it. It doesn't seem a issue with the tf provider, moreover with dns configuration on the OS. 

If adding the node dns registry to your hosts file is working fine, then probably something is not working completely fine on your vpn dns configuration. 

Anyway, if you think there is an issue with dns configuration on terraform, should be better if you open an issue in terraform repo.

**Comment by rawmind0** [comment]
Due to rancher2 terraform provider is already officially supported by Hashicorp, this repo is going to be archived.

Please consider reopen issue on https://github.com/terraform-providers/terraform-provider-rancher2 if needed.
