### ISSUE TITLE
Support RKE DNS Configuration

### ISSUE THREAD

**Issue by dahendel** [rancher/terraform-provider-rancher2-archive#82]
I started working on supporting DNS config under RKE, however looks like rancher types dependency in vendor does not include the DNS config. I am testing locally with the updated rancher types to the latest commit. When I am ready should I submit the PR with the vendor change or would you guys like to handle that?

**Comment by dahendel** [comment]
This sounds like it might get added in #65 by way of an updates required to implement that feature.

**Comment by rawmind0** [comment]
@dahendel, rancher v2.2 is still not supported by this provider. We are on the way to support it asap.

**Comment by dahendel** [comment]
@rawmind0 Thanks for update. Looking forward to it. I will go ahead and close this.

**Comment by rawmind0** [comment]
Added support to rke dns config on PR #85
