### ISSUE TITLE
"provider's website" link in README.md DNE

### ISSUE THREAD

**Issue by jlund69** [rancher/terraform-provider-rancher2-archive#83]
README.md link

- [provider's website](https://www.terraform.io/docs/providers/rancher2/index.html).

is a 404 not found.

Currently only 
https://www.terraform.io/docs/providers/rancher/index.html is an active link on the terraform site.

**Comment by apricote** [comment]
It is probably already pointing to the new location of the docs. It will work once the provider has been accepted as an "offical provider".

Check out #67 to see the progress on that.

**Comment by rawmind0** [comment]
As @apricote  said, this link will not be working until the provider has been accepted as an official provider. You could see the docs of the provider on this folder, https://github.com/rancher/terraform-provider-rancher2/tree/master/website/docs/r

**Comment by rawmind0** [comment]
@jlund69, rancher 2 provider is already published as an official terraform provider. Documentation is also live and published, https://www.terraform.io/docs/providers/rancher2/index.html

Please, reopen issue if needed.
