### ISSUE TITLE
Adding Addition Cloud Provider Data

### ISSUE THREAD

**Issue by jamiebuxxx** [rancher/terraform-provider-rancher2-archive#86]
Hello,

I'm trying to add the following cloud provider configuration via the Rancher Terraform plugin:
https://github.com/rancher/rancher/issues/17345#issuecomment-467653203.

However, I'm getting an error when including this data to my plan. The README list that were should be a max item of 1. 

```
Error: rancher2_cluster.k8s_rancher_cluster: rke_config.0.cloud_provider.0.custom_cloud_provider must be a single value, not a list
```

I figured this is probably not scoped to handle this addition arguments. 

It would be cool to either include an json/yaml file for RKE specific configs(like the `--rke-config ` flag from the Rancher2 CLI) or scope the additional configs into the cluster resource

**Comment by rawmind0** [comment]
Hi @jamiebuxxx, 

how are you adding cloud provider configuration in your tf file??
The arguments supported for `cloud_provider` on rke clusters are defined in the [docs]( https://github.com/rancher/terraform-provider-rancher2/blob/master/website/docs/r/cluster.html.markdown#cloud_provider)

Should work with a tf file like that,
```
resource "rancher2_cluster" "test" {
  name = "test"
  rke_config {
    network {
      plugin = "canal"
    }
    cloud_provider {
      custom_cloud_provider = "test"
    }
  }
}
```

**Comment by jamiebuxxx** [comment]
Hi @rawmind0 
I think my question more specifically is how does one add nested values to the `custom_cloud_provider`. The YAML for the value I want to set looks like this:
```
cloud_provider:
  name: aws
  awsCloudProvider:
    global:
      disable-security-group-ingress: true
```
Since the `cloud_provider` only take a single value, is it possible to add additional data for a specific cloud provider?

**Comment by rawmind0** [comment]
@jamiebuxxx , `custom_cloud_provider` doesn't have nested values on rke. 

`cloud_provider` doesn't take a single value as you can see at docs. 

The config you are pasting is `aws` cloud provider not `custom`.  Unfortunatelly, `aws_cloud_provider` is on the way but not supported yet by this provider.

**Comment by jamiebuxxx** [comment]
Ah, I see. Thanks for clearing this up @rawmind0! Do you have an ETA on the `aws_cloud_provider`?

**Comment by rawmind0** [comment]
Added support to rke `aws_cloud_provider` on PR #90
