### ISSUE TITLE
Add vSphere node template

### ISSUE THREAD

**Issue by ernst-at-tv2** [rancher/terraform-provider-rancher2-archive#89]
We'd really like to use this provider to provision vSphere clusters through Rancher 2, but it would seem that the vSphere node template hasn't been implemented yet?

**Comment by rawmind0** [comment]
@ernst-at-tv2, vsphere node template is not yet implemented in this provider. We are working to provide new features on the provider, but still no ETA for vsphere node template support.

**Comment by rawmind0** [comment]
Added support to vsphere cloud credential and node template on PR #91

**Comment by rawmind0** [comment]
Please, reopen if needed.
