### ISSUE TITLE
Unable to create a cluster on AWS when access key and secret key is specified in ENV

### ISSUE THREAD

**Issue by ishantanu** [rancher/terraform-provider-rancher2-archive#92]
Hi,

I am facing an issue with this provider when I am trying to pass AWS access key and secret key via env var.

The config files are something like this:
```
# Provider config
provider "rancher2" {
  api_url    = "https://rancher.xyz.com/v3"
  access_key = "XXXXXXX"
  secret_key = "XXXXXXX"
}

# Create a new rancher2 rke Cluster
resource "rancher2_cluster" "foo-custom" {
  name        = "foo-custom"
  description = "Foo rancher2 custom cluster"

  rke_config {
    network {
      plugin = "canal"
    }

    cloud_provider {
      name = "aws"
    }
  }
}

# Create a new rancher2 Node Template
resource "rancher2_node_template" "foo" {
  name        = "foo"
  description = "foo test"

  amazonec2_config {
    access_key     = "${var.AWS_ACCESS_KEY_ID}"
    secret_key     = "${var.AWS_SECRET_ACCESS_KEY}"
    ami            = "${var.ami}"
    region         = "${var.region}"
    security_group = ["${var.security_group_id}"]
    subnet_id      = "${var.subnet_id}"
    vpc_id         = "${var.vpc_id}"
    zone           = ""
    instance_type  = "t2.medium"
  }
}

# Create a new rancher2 Node Pool
resource "rancher2_node_pool" "foo" {
  cluster_id       = "${rancher2_cluster.foo-custom.id}"
  name             = "foo"
  hostname_prefix  = "foo-cluster-0"
  node_template_id = "${rancher2_node_template.foo.id}"
  quantity         = 3
  control_plane    = true
  etcd             = true
  worker           = true
}
```

`credentials.tfvars`:
```
AWS_ACCESS_KEY_ID = ""
AWS_SECRET_ACCESS_KEY = ""
AWS_SSH_KEY_NAME = ""
AWS_DEFAULT_REGION = "eu-central-1"
```

And, I have exported these vars. But, when I run `terraform apply`, it shows error on the Rancher GUI that `access_key` and `secret_keys` are invalid.

On the other hand, if I pass these values directly as `access_key     = "XXXXXXXXXXX"` in `amazonec2_config`, it works.

**Comment by rawmind0** [comment]
@ishantanu, if provider is working fine if you set these values directly, probably you are not setting your environment variables correctly. 

In terraform, the environment variables must be in the format `TF_VAR_name`, are them set in this format??
https://www.terraform.io/docs/commands/environment-variables.html#tf_var_name

**Comment by ishantanu** [comment]
@rawmind0 Yes, they are.
```
TF_VAR_AWS_ACCESS_KEY_ID=XXXXXXXX
TF_VAR_AWS_SECRET_ACCESS_KEY=XXXXXX
```

**Comment by ishantanu** [comment]
Just FYI, this is what the error looks like:
![Screenshot 2019-05-09 at 11 24 34 PM](https://user-images.githubusercontent.com/6175822/57475293-a97f9780-72b1-11e9-961e-76d189ed1140.png)

**Comment by ishantanu** [comment]
Okay. Sorry for the noise, I was passing empty values via `credentials.tfvars` after setting env vars. And `credentials.tfvars` were overriding the values which I set in env. Closing this.
