### ISSUE TITLE
Unable to install docker on the nodes provisioned by the provider

### ISSUE THREAD

**Issue by ishantanu** [rancher/terraform-provider-rancher2-archive#93]
Hi,

I managed to create a cluster along with node template and node pools for AWS. The nodes were launched as well. But, they all errored out one after another saying "Unable to install docker". A screenshot of the error message is attached. 
![Screenshot 2019-05-09 at 6 13 33 PM](https://user-images.githubusercontent.com/6175822/57454717-1b8eb700-7287-11e9-861c-584d63ba3d84.png)

This screenshot shows just one node but they all error out by the same message. After that, these instances get terminated and new ones are launched which again shows the error. The cycle doesn't stop until I run `terraform destroy`. Is there anything I am missing?

**Comment by rawmind0** [comment]
@ishantanu, is this configuration working fine if you apply it from the UI?? What AMI and OS are you trying to deploy??  Node template is using docker machine with aws driver to deploy vm's, please, check that you ami is compatible with it, https://docs.docker.com/machine/drivers/aws/

**Comment by ishantanu** [comment]
@rawmind0 I was trying Ubuntu 18.04 AMI in eu-central-1 region. Weird that it is not working from the terraform provider but, when I create node template, node pool, and cluster from GUI, it works.

The AMI ID which I am trying is `ami-090f10efc254eaf55`. I can confirm that there's no difference between the node template which gets generated by the provider and another working node template  I use from GUI (having the same AMI IDs).

**Comment by rawmind0** [comment]
Yes, it seems weird... What rancher version are you using?? Could you please paste your tf file?? 

I've just tested on rancher v2.2.2 with Ubuntu 16.04 LTS (default version on docker machine) and it's working fine. 

With ubuntu 18.04 LTS is failing due to vm is continuously restarting on aws. It seems that ami has something wrong. Could you please try with ubuntu 16.04 ami??

This is the tf file that is working fine for me...
```
resource "rancher2_cluster" "test" {
  name = "test"
  rke_config {
    network {
      plugin = "canal"
    }
    services {
      etcd {
        creation = "12h"
        retention = "72h"
        backup_config {
          enabled = false
          interval_hours = 24
          retention = 12
        }
      }
    }
  }
}
resource "rancher2_cloud_credential" "test" {
  name = "test"
  amazonec2_credential_config {
    access_key = "<AWS_ACCESS_KEY>"
    secret_key = "<AWS_SECRET_KEY>"
  }
}
resource "rancher2_node_template" "test" {
  name = "test"
  cloud_credential_id = "${rancher2_cloud_credential.test.id}"
  amazonec2_config {
    ami =  "ami-6d48500b"
    instance_type = "t2.medium"
    region = "eu-west-1"
    security_group = ["<SEC_GROUPS>"]
    subnet_id = "<SUBNET_ID>"
    vpc_id = "<VPC_ID>"
    zone = "<ZONE>"
  }
}
resource "rancher2_node_pool" "test" {
  cluster_id =  "${rancher2_cluster.test.id}"
  name = "test"
  hostname_prefix =  "test-cluster-0"
  node_template_id = "${rancher2_node_template.test.id}"
  quantity = 3
  control_plane = true
  etcd = true
  worker = true
}
```

**Comment by ishantanu** [comment]
Okay. Ubuntu 16.04 AMI works fine. But, what about 18.04? It should work from the provider if it is working from the GUI.

**Comment by rawmind0** [comment]
For me, 18.04 ami is not working neither from the UI.

**Comment by ishantanu** [comment]
I'd urge you to give it a try in `eu-central-1` region by creating everything from GUI. Here are the working screenshots:
![Screenshot 2019-05-10 at 1 03 09 PM](https://user-images.githubusercontent.com/6175822/57510410-5abf1580-7324-11e9-9774-d20982ab9884.png)
![Screenshot 2019-05-10 at 1 04 03 PM](https://user-images.githubusercontent.com/6175822/57510411-5b57ac00-7324-11e9-80bb-62af60444e67.png)


It not only works in eu-central-1 but I've also successfully used Ubuntu 18.04 in us-east-1 for one of our deployments. Both without issues and running fine.

**Comment by rawmind0** [comment]
@ishantanu  you are right, working with this image. Good new is that i found the difference, that is the docker install url.

To make it work from provider, add `engine_install_url = "https://releases.rancher.com/install-docker/18.09.sh"` parameter to your node_template resource and should work fine.

```
resource "rancher2_node_template" "test" {
  name = "test"
  cloud_credential_id = "${rancher2_cloud_credential.test.id}"
  engine_install_url = "https://releases.rancher.com/install-docker/18.09.sh"
  amazonec2_config {
    ami =  "ami-090f10efc254eaf55"
    region = "eu-central-1"
    instance_type = "t2.medium"
    security_group = ["<SEC_GROUPS>"]
    subnet_id = "<SUBNET_ID>"
    vpc_id = "<VPC_ID>"
    zone = "<ZONE>"
  }
}
```

**Comment by ishantanu** [comment]
Yes, that was it. It is working now. Thanks. Will this be documented somewhere? Or will you be changing the docker install URL?

**Comment by rawmind0** [comment]
`engine_install_url` argument is already documented on provider doc. Default value is just failing with ubuntu 18.04, working fine on 16.04. We'll check if docker version is working fine everywhere and we'll update default `engine_install_url` value accordingly.

**Comment by rawmind0** [comment]
Due to rancher2 terraform provider is already officially supported by Hashicorp, this repo is going to be archived.

Please consider reopen issue on https://github.com/terraform-providers/terraform-provider-rancher2 if needed.
