### ISSUE TITLE
rancher2_cluster resource accepts unsupported `kubernetes_version` values

### ISSUE THREAD

**Issue by timobartels** [rancher/terraform-provider-rancher2-archive#96]
tested [version](https://github.com/rancher/terraform-provider-rancher2/releases/tag/v0.2.0-rc5) v0.2.0-rc5

For an existing Kubernetes cluster (managed by Rancher), providing a `kubernetes_version` to the `rancher2_cluster` resource that is unknown/unavailable to Rancher (eg. `v1.14.1-rancher`), the upgrade will not take place and terraform will run into a timeout. Bad side-effect, terraform will write the new/invalid version into the statefile, and the next `terrafom apply` will expect the cluster to have the the invalid Kubernetes version.

Not sure whether the problem is in the terraform provider (that doesn't handle the exceptions thrown by Rancher API), or whether Rancher API doesn't respond properly that the version is invalid.

**Comment by rawmind0** [comment]
@timobartels, terraform provider is checking errors or exceptions thrown by rancher API. I think the problem may be at rancher API that seems is not checking valid kubernetes version. 

Could you please open issue on rancher/rancher repo??

**Comment by rawmind0** [comment]
Due to rancher2 terraform provider is already officially supported by Hashicorp, this repo is going to be archived.

Please consider reopen issue on https://github.com/terraform-providers/terraform-provider-rancher2 if needed.
