### ISSUE TITLE
Feature Request - data source to fetch rancher project ids

### ISSUE THREAD

**Issue by robertgates55** [rancher/terraform-provider-rancher2-archive#98]
Thanks for all the hard work getting the provider into the official providers set - it's great not to have to manually compile it any more!

I have kubernetes resources (eg a namespace) being created using the terraform provider.

After importing the cluster to rancher, to see the namespace I have to first move it to a rancher Project (eg 'Default')

However, at this point my next terraform apply will remove the resources from that project, by removing the rancher-added annotations from the kubernetes resource. I could fix this by setting the rancher annotation myself in the kubernetes terraform resource, but I don't believe I can dynamically fetch the project id from anywhere.

So - feature time:
It'd be great if there were a data source that could fetch me the cluster/project ids for a cluster, such that I could add the relevant annotation to the kubernetes resources to ensure they stay in the correct project.

**Comment by robertgates55** [comment]
Realised I could create a project using the rancher2_project resource, but ideally I'd just like to move to the 'Default' project directly.

**Comment by rawmind0** [comment]
Hi @robertgates55,

i understand that you are importing/moving k8s namespaces using rancher2 terraform provider, isn't it?? Have you consider to create k8s namespace using rancher2_namespace resource??

Anyway, we are thinking to add datasources to the provider, that could fetch info from projects and clusters.

**Comment by robertgates55** [comment]
I did consider using the rancher2_namespace resource, but then even that requires me to pass a project ID... so I still need to either have created it using rancher2_project, or just have to know the default project id.

**Comment by rawmind0** [comment]
@robertgates55 , i'm finishing a fix that add `default_project_id` and `system_project_id` to the cluster resources. With that, you could create namespaces assigned to default cluster project, without knowing project ID. May this work for you??

EG
```
# Create a new rancher2 Cluster 
resource "rancher2_cluster" "foo" {
  name = "foo"
  description = "Foo rancher2 custom cluster"
  rke_config {
    network {
      plugin = "canal"
    }
  }
}
# Create a new rancher2 Namespace assigned to default cluster project
resource "rancher2_namespace" "foo" {
  name = "foo"
  project_id = "${rancher2_cluster.foo.default_project_id}"
  description = "foo namespace"
}
```

**Comment by rawmind0** [comment]
Additionally, a new option will be added on namespace resource import. Being able to import a namespace and move it or not to a project.

BTW, we are deprecating this repo in favour of [hashicorp official repo](https://github.com/terraform-providers/terraform-provider-rancher2). PR will be submitted there.

**Comment by rawmind0** [comment]
Fixed by https://github.com/terraform-providers/terraform-provider-rancher2/pull/8

**Comment by rawmind0** [comment]
Due to rancher2 terraform provider is already officially supported by Hashicorp, this repo is going to be archived.

Please consider reopen issue on https://github.com/terraform-providers/terraform-provider-rancher2 if needed.
